name: internet_connection_status
description: A Flutter package to detect internet connection and show banners
version: 1.0.0
homepage: https://github.com/programmerhasan/flutter_internet_connection_status
repository: https://github.com/programmerhasan/flutter_internet_connection_status
issue_tracker: https://github.com/programmerhasan/flutter_internet_connection_status/issues
documentation: https://pub.dev/packages/flutter_internet_connection_status

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

features:
  - Automatic internet connection detection using connectivity_plus and internet_connection_checker
  - Shows online/offline status banners automatically
  - Stylish blur glass-effect banners for online/offline status notifications
  - Customizable banners via widget or text parameters
  - Built with hooks_riverpod and flutter_hooks for reactive and declarative usage

topics:
  - connectivity
  - internet
  - network
  - status
  - flutter
  - hooks
  - riverpod
  - flutter-hooks
  - connectivity-status
  - internet-status
  - online-offline

screenshots:
  - description: "Internet Connection Status Logo"
    path: screenshots/online_offline_status.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0